version: '3'
services:
    jupytertest:
        build: notebook
        ports:
            - '8890:8888'
        volumes:
            - "c:/FWS/02Docker/cheminfo/01WorkSpace:/home/jovyan/notebooks"
        environment: 
            GRANT_SUDO: "yes"
        command: 
            start-notebook.sh